# find_package(absl CONFIG REQUIRED)
find_package(Catch2 CONFIG REQUIRED)
find_package(constexpr-contracts CONFIG REQUIRED)
# find_package(fmt CONFIG REQUIRED)
find_package(glfw3 CONFIG REQUIRED)
find_package(glm CONFIG REQUIRED)
find_package(Vulkan REQUIRED)
